# Generated by Django 3.1.1 on 2020-10-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
