# Generated by Django 3.1.1 on 2020-11-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='franchise',
        ),
    ]
